#!/bin/sh

# Order items in "for" cykles from most important one to
#   one with lowest priority
#   high resolutions first

for type in ";.svg" ";.png" ";.xpm" ""; do
  for path in '/usr/share/icons' \
              '/usr/share/pixmaps' \
              '/usr/include/X11/bitmaps'; do
    find $path -type d |
    grep -iv cursors |
    grep -iv locolor |
    sed -r 's|^(.+?/[0-9]+x([0-9]+).+?)$|\1:\2|' |
    sort -t ':' -k 2,2 -n -r |
    cut -d ':' -f1 |
    sed -r 's|(.*)$|ImagePath +:\1'$type'|'
  done
done
