#!/bin/sh

# Generate KDM poweroff menu.
# usage: sh_poweroffmenu-kdm menu1 menu2
#  menu1 = name of menu, where to place power off functionality
#  menu2 = name of menu, where to place locking, etc. possibilities

echo AddToMenu $1 \"KDM generovani neni hotove\" Nop
echo AddToMenu $2 \"KDM generovani neni hotove\" Nop
